-- SQLite

-- Creating CARS table

CREATE TABLE CARS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(120) NOT NULL,
    YEAR INTEGER NOT NULL, 
    COLOR VARCHAR(32) NOT NULL,
    KM FLOAT(10,2) NOT NULL,
    STATUS VARCHAR(17),
    BRAND_ID INTEGER,
    MODEL_ID INTEGER,
    
    FOREIGN KEY (BRAND_ID) REFERENCES CAR_BRAND (ID)
    FOREIGN KEY (MODEL_ID) REFERENCES CAR_MODELS (ID)
);