-- SQLite

-- Creating LOCATIONS table 

CREATE TABLE LOCATIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    TOTAL FLOAT(10,2) NOT NULL, 
    CUSTOMER_ID INTEGER NOT NULL,
    CAR_ID INTEGER NOT NULL, 
    EMPLOYEE_ID INTEGER NOT NULL,

    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID)
    FOREIGN KEY (CAR_ID) REFERENCES CARS (ID)
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID)
);