-- SQLite

-- Search all employees with their respective positions

SELECT NAME, PHONE_NUMBER, CONTRACT_DATE, POSITIONS.DESCRIPTION AS POSITION
    FROM EMPLOYEES 
    INNER JOIN POSITIONS ON EMPLOYEES.POSITION_ID=POSITIONS.ID;