-- SQLite

-- Search all locations with their respectives customer, car and employee

SELECT START_DATE, END_DATE, TOTAL, CUSTOMERS.NAME AS CUSTOMER, CARS.NAME AS CAR, EMPLOYEES.NAME AS EMPLOYEE 
    FROM LOCATIONS
    INNER JOIN CUSTOMERS 
        ON LOCATIONS.CUSTOMER_ID=CUSTOMERS.ID
    INNER JOIN CARS 
        ON LOCATIONS.CAR_ID=CARS.ID 
    INNER JOIN EMPLOYEES 
        ON LOCATIONS.EMPLOYEE_ID=EMPLOYEES.ID;